services:
  - type: web
    name: flask-bus-bot
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: BUS_API_KEY
        value: KfRiwhzgjPeFG9rviJvkpCjnr
      - key: RTPIDATAFEED
        value: bustime
      - key: MESSAGE_LIMIT
        value: "8"
